#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image: Visual Studio 2022
configuration: Release
environment:
  NUGET_TOKEN:
    secure: Iew1Z5vVgZAv7R9I51ZGqhSsB8d/byNMBvtmi4uHDSkCh8CVW8y1OiTRgrxuM3Zg
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
build_script:
- ps: .\build.ps1
test: off
